version: '3.3'
services: 
  post_db:
    image: mongo:3.2
    volumes: 
      - post_db:/data/db
    networks: 
      - reddit_backend
  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${MS_UI_VERSION}
    ports: 
      - ${MS_UI_PORT}:${MS_UI_PORT}/tcp
    networks:
      - reddit_frontent
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${MS_POST_VERSION}
    networks: 
      - reddit_frontent
      - reddit_backend
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${MS_COMMENT_VERSION}
    networks:
      - reddit_frontent
      - reddit_backend
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes: 
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks: 
        - reddit_backend
        - reddit_frontent
  node_exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks: 
      - reddit_backend
volumes: 
  post_db:
  prometheus_data:

networks: 
  reddit_frontent:
  reddit_backend:
