version: '3.3'
services: 
  post_db:
    image: mongo:3.2
    volumes: 
      - post_db:/data/db
    networks: 
      - reddit
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${MS_UI_VERSION}
    ports: 
      - ${MS_UI_PORT}:${MS_UI_PORT}/tcp
    networks: 
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${MS_POST_VERSION}
    networks: 
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${MS_COMMENT_VERSION}
    networks:
      - reddit
volumes: 
  post_db:

networks: 
  reddit:
  